name: Read Google Sheet with Python

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  read-sheet:
    runs-on: ubuntu-latest
    environment: Lifisher_Sheet_Secrets  # 指定环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client

      - name: Read Google Sheet
        env:
          SHEET_KEY: ${{ secrets.SHEET_KEY }}  # 从 Secrets 中获取 JSON 密钥
          SHEET_ID: ${{ secrets.SHEET_ID }}    # 从 Secrets 中获取 Sheet ID
        run: |
          echo "$SHEET_KEY" > credentials.json
          python read_google_sheet.py
