name: run update

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    environment: Lifisher_Sheet_Secrets  # 指定环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        env:
          R_LIBS_USER: /home/runner/work/_temp/Library  # 显式设置 R 包库路径
        run: |
          R -e 'install.packages("googlesheets4", repos = "https://cloud.r-project.org", lib = "/home/runner/work/_temp/Library")'

      - name: Check if googlesheets4 is installed
        env:
          R_LIBS_USER: /home/runner/work/_temp/Library  # 显式设置 R 包库路径
        run: |
          R -e 'library(googlesheets4)'

      - name: Update Google Sheet
        env:
          SHEET_KEY: ${{ secrets.SHEET_KEY }}  # 从 Secrets 中获取 JSON 密钥
          SHEET_ID: ${{ secrets.SHEET_ID }}    # 从 Secrets 中获取 Sheet ID
          R_LIBS_USER: /home/runner/work/_temp/Library  # 显式设置 R 包库路径
        run: |
          Rscript read-google-sheet.R
