name: run update

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    environment: Lifisher_Sheet_Secrets  # 指定环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          mkdir -p $HOME/R/library
          echo "R_LIBS_USER=$HOME/R/library" >> $GITHUB_ENV
          R -e 'install.packages("googlesheets4", repos = "https://cloud.r-project.org")'

      - name: Update Google Sheet
        env:
          SHEET_KEY: ${{ secrets.SHEET_KEY }}  # 从 Secrets 中获取 JSON 密钥
          SHEET_ID: ${{ secrets.SHEET_ID }}    # 从 Secrets 中获取 Sheet ID
        run: |
          Rscript read-google-sheet.R
