name: Run R Script

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: Lifisher_Sheet_Secrets  # 指定环境名称
    steps:
      - uses: actions/checkout@v3  # 拉取代码

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev  # 安装 libcurl 和 libxml2 系统依赖

      - name: Cache R packages
        id: cache-r-packages
        uses: actions/cache@v3
        with:
          path: ~/.R/library  # R 依赖包的默认安装路径
          key: r-packages-${{ hashFiles('**/DESCRIPTION') }}  # 根据 DESCRIPTION 文件生成缓存键
          restore-keys: |
            r-packages-

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("httr", "dplyr", "jsonlite", "tidyr", "googlesheets4"), repos="https://cloud.r-project.org")'

      - name: Create credentials file
        run: echo '${{ secrets.SHEET_KEY }}' > credentials.json
          
      - name: Run R script
        run: Rscript GetFile.R
        env:
          LIFISHER_CODES: ${{ secrets.LIFISHER_CODES }}
          LIFISHER_TOKEN: ${{ secrets.LIFISHER_TOKEN }}
          LIFISHER_VARIABLES: ${{ vars.LIFISHER_VARIABLES }}
          SHEET_ID: ${{ secrets.SHEET_ID }}

      - name: Remove credentials file
        run: rm credentials.json

      - name: Notify on success
        if: success()
        run: |
          echo "R script ran successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "R script failed!"



          
